### ISSUE TITLE
Lots of Crash captured by Crashlytics

### ISSUE THREAD

**Issue by mauriciovr13** [Survicate/survicate-react-native-sdk#73] opened 2024-01-26 14:36 UTC
I'm getting a lot of logs of this same error in my crashlytics, but I don't understand why. I followed the survicate configuration step by step and didn't encounter any similar problems here. Previously we used version 1.1.16 and then updated to 3.1.0 to see if the crash stopped, but without success

Library info:
- "@survicate/react-native-survicate": "^3.1.0"
- "react-native": "0.67.4"

Error log:
```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.myApp/com.survicate.surveys.SurveyActivity}: java.lang.NullPointerException: Attempt to read from field 'com.survicate.surveys.presentation.base.DisplayEngine com.survicate.surveys.Survicate.displayEngine' on a null object reference in method 'void com.survicate.surveys.SurveyActivity.<init>()'
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3914)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by SurvicatePawelGodlewski** [comment] 2024-01-30 07:26
@mauriciovr13 Hey, if I understand correctly you previously had v1.1.16 and the issue occured in that version and after update to 3.1.0 the issue persists?

**Comment by mauriciovr13** [comment] 2024-01-30 18:16
@SurvicatePawelGodlewski Exactly

**Comment by SurvicatePawelGodlewski** [comment] 2024-01-31 12:13
@mauriciovr13 We will look into this issue. Is there any pattern in those crashes (e.g. API version, specific devices)? What AGP and Gradle versions do you use and have they changed since first crashes?

**Comment by mauriciovr13** [comment] 2024-01-31 17:29
@SurvicatePawelGodlewski I couldn't find any pattern in these failures, the list of devices and Android versions is quite varied. The only insight that appears is the message: "This failed event happened in the first second of the user session."

These are the AGP and Gradle versions, there has been no change to them since the first crash.

![Captura de Tela 2024-01-31 às 14 20 28](https://github.com/Survicate/survicate-react-native-sdk/assets/28811382/705e0b04-0893-4ff9-921f-8d09d00cf599)

**Comment by SurvicatePawelGodlewski** [comment] 2024-02-01 11:24
@mauriciovr13 We were able to reproduce this issue on our side. We are now working on it and plan to release this with the next version update.

**Comment by SurvicatePawelGodlewski** [comment] 2024-02-14 08:51
@mauriciovr13 Thank you very much for your patience. We have released v4.0.2 that addresses the issue

**Comment by SurvicatePawelGodlewski** [comment] 2024-02-26 06:51
As the issue is fixed I am closing this issue

**Closed by SurvicatePawelGodlewski** 2024-02-26 06:51 UTC
Labels: bug

**Comment by mauriciovr13** [comment] 2024-02-26 13:41
Thanks for the issue fixed!
